<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RunAOTCompilation>true</RunAOTCompilation>
		<!--<WasmStripILAfterAOT>true</WasmStripILAfterAOT>-->
		<!--<WasmEnableSIMD>false</WasmEnableSIMD>-->
		<CompressionEnabled>false</CompressionEnabled>

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Masa.Blazor" Version="1.11.9" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.8" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Maple.MonoGameAssistant.GameCore\Maple.MonoGameAssistant.GameCore.csproj" />
		<ProjectReference Include="..\Maple.MonoGameAssistant.GameShared\Maple.MonoGameAssistant.GameShared.csproj" />
	</ItemGroup>

</Project>
